dietsource/blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	#home-page
    #url(r'^$', views.index , name="index" ),
    url(r'^blog/$', views.post_list , name="index" ),
    url(r'^faq/$', views.faq , name="faq" ),
    url(r'^category/(?P<cat_slug>[a-zA-Z0-9-]+)/$', views.category_list_view , name="category" ),
    url(r'^tag/(?P<tag_slug>[a-zA-Z0-9-]+)/$', views.tag_list_view , name="tag" ),
    url(r'^(?P<post_slug>[a-zA-Z0-9-]+)/$', views.post_detail , name="post" ),

]

dietsource/dietplate/urls.py
"""
Definition of urls for notesformca.
"""
from django.conf import settings
from django.conf.urls.static import static
from datetime import datetime
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
from . import views
admin.autodiscover()

urlpatterns = [
    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),


    # Uncomment the next line to enable the admin:

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^$', views.index , name="index" ),
    url(r'^about/$', views.about , name="about" ),
    url(r'^contact/$', views.contact , name="contact" ),
    url(r'^contact/success/$', views.contact_success , name="contact_success"),
    url(r'^book-appointment/$', views.book_appointment , name="book_appointment"),
    # url(r'^chaining/', include('smart_selects.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    #url(r'^service/', include("services.urls", namespace='service')),
    url(r'^', include('blog.urls', namespace = 'blog')),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

dietsource/services/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	#home-page
    #url(r'^$', views.index , name="index" ),
    url(r'^$', views.services , name="services" ),
    url(r'^(?P<service_slug>[a-zA-Z0-9-]+)/$', views.service_detail , name="service_detail" ),


]

dietsource/services/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor_uploader.image import pillow_backend as backend
from django.db.models.signals import post_save,pre_save
from captcha.fields import ReCaptchaField


class Subscriber(models.Model):
    """docstring for ClassName"""
    email=models.EmailField(max_length=254,unique=True)
    is_subscribed = models.BooleanField(default=True)


class ServiceManager(models.Manager):
    def active(self, *args, **kwargs):
        # Service.objects.all() = super(ServiceManager, self).all()
        return super(ServiceManager, self).filter(is_active=True).filter(published_on__lte=timezone.now())


def upload_location(instance, filename):
    return "featured_service_images/%s/%s" %(instance.id, filename)

class Service(models.Model):
    author = models.ForeignKey(User, null=True, blank=True, editable = False)
    name = models.CharField(max_length=50,unique=True)
    slug = models.CharField(max_length =10,null=True,blank=True)
    seo_desc = models.CharField(max_length=160,blank=True,null=True,unique=True,help_text="This must not be more than 160 characters and must relate to Service")
    seo_keywords = models.CharField(max_length=350,blank=True,null=True,help_text="Try to keep list in Longest to shortest Keyword order. Must contain comma seperated list of key words.")
    featured_image = models.ImageField(upload_to=upload_location, 
            null=True, 
            blank=True)
    content = RichTextUploadingField(null=True,blank=True)
    is_active = models.BooleanField(default=False)
    published_on = models.DateField(auto_now=False, auto_now_add=False,null=True,blank=True)
    last_updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    created_on = models.DateTimeField(auto_now=False, auto_now_add=True)
    
    objects = ServiceManager()
    def __str__(self):
        return self.name

    def clean(self):
        self.name = self.name.capitalize()

    def image_thumb(self):
        if self.featured_image :
            return '<img src="/media/%s" width="120" height="90" />' % (self.featured_image)
        return '<img src="/media/featured_post_images/default-featured-image.png" width="120" height="90" />'
    image_thumb.allow_tags = True  

    def get_absolute_url(self):
        context = {
        'service_slug':self.slug,
        }
        return reverse("service:service_detail", kwargs=context)

    def save(self, *args, **kwargs):
        if self.id and self.featured_image:
        #checking if previous image is not equalt to current image delete previous image
            try:
                this = Service.objects.get(id=self.id)
                if this.featured_image != self.featured_image:
                    this.featured_image.delete()
            except: pass # when new photo then we do nothing, normal case
        super(Service, self).save(*args, **kwargs)
        if self.featured_image:
            backend.create_thumbnail(self.featured_image.name)

class Appointment(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField(max_length=254)
    number = models.CharField(max_length=13,blank=True,null=True)
    service = models.ForeignKey(Service,blank=True,null=True)
    message = models.TextField()    
    seen = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name
    def clean(self):
        self.name = self.name.capitalize()


def pre_save_service_receiver(sender, instance, *args, **kwargs):
	##setting publish date 
    if instance.is_active == True and not instance.published_on:
        instance.published_on = timezone.now()
    instance.slug =slugify(instance.name) #create_slug(instance)

pre_save.connect(pre_save_service_receiver, sender=Service)

dietsource/services/forms.py
from django import forms
from django.core.exceptions import ValidationError
from captcha.fields import ReCaptchaField
from .models import Appointment, Subscriber

class AppointmentForm(forms.ModelForm):
   # captcha = ReCaptchaField()
    class Meta:
        model = Appointment
        fields = ['name','email','number','service','message']

    def __init__(self, *args, **kwargs):
        super(AppointmentForm, self).__init__(*args, **kwargs)
        self.fields['service'].empty_label = '--Select your concern--'

    def clean_number(self):
        print self.cleaned_data
        client_phone = self.cleaned_data['number']
        if client_phone.isdigit() and not client_phone.isalpha():
            min_length = 10
            max_length = 12
            ph_length = str(client_phone)
            if len(ph_length) < min_length or len(ph_length) > max_length:
                raise ValidationError('Phone number length not valid')
        else:
            raise ValidationError('Please enter a valid phone number')
        return client_phone


dietsource/services/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import Context
from django.shortcuts import render,get_list_or_404,get_object_or_404
from django.core.urlresolvers import reverse
from .models import Service


# Create your views here.
def services(request):
	all_services = Service.objects.active().order_by('name')
	context = Context({
		'all_services':all_services,
		'title': "Services"
		})

	return render(request, "services/services_list.html",context)

def service_detail(request , service_slug):
	service = get_object_or_404(Service,slug=service_slug )
	context = Context({
		'service':service,
		'title': service.name,
		})

	return render(request, "services/services_detail.html",context)

dietsource/templates/services/appointment_form.html
<div class="modal fade" id="appoint" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
      <h3 class="modal-title" id="lineModalLabel">Book an Appointment</h3>
    </div>
    <div class="modal-body">
      <form class="ajax-form" id ="id-appointment-form" name="appointment-form" method="post" action="{% url 'book_appointment' %}">
              {% csrf_token %}           
                 <div class="row">
                    <div class="col-sm-6">
                      <div class="form-group">
                        <input type="text" name="name" class="form-control" placeholder="Name" required="required">
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="form-group">
                        <input type="email" name="email" class="form-control" placeholder="Email Address" required="required">
                      </div>
                    </div>
                  </div>
                  <div class="row ">
                    <div class="col-sm-6">
                      <div class="form-group">
                        <input type="text" name="number" class="form-control" placeholder="Phone" required="required">
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="form-group">
                        <select id="id_service" type="select" name="service" class="form-control" required="required">
                          {% for id,name in form.service.field.choices %}
                              <option value="{{ id }}"{% if form.fields.service.value == id %} selected{% endif %}>{{ name }}</option>
                          {% endfor %}
                        </select>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <textarea name="message" id="message" class="form-control" rows="4" placeholder="Enter your message" required="required"></textarea>
                  </div> 
                 <div class="form-group">
                   {{form.captcha}}
                  </div>                   
                  <div class="form-group">
                    <button type="submit" class="btn btn-warning btn-lg btn-block">Send Now</button>
                  </div>
      </form>

    </div>
  </div>
  </div>
</div>

dietsource/templates/services/bmiForm.html
 <div class="bmi-calculator wow flipInY" data-wow-duration="1000ms" data-wow-delay="300ms">
  <form class="form-horizontal form-bmi" role="form">
  <p class="heading">BMI Calculator</p>
    <div class="bmi-weight">
      <div class="form-horizontal">
        <label for="weight">How much do you weigh?</label>
          <div class='input-group'>
              <input id="weight-value" class='form-control' type='text' name='weight-name'  placeholder='Enter your weigh'/>
                <span class='input-group-btn'>
                  <div class="btn-group">
                    <button type="button" class="btn bmi-btn  btn-block weight active-weight selected-weight" id='kg'>kg</button>
                  </div>
                  <div class="btn-group">
                    <button type="button" class="btn bmi-btn  btn-block weight" id='lbs'>lbs</button>
                  </div>                          
                </span>
          </div>
        <input name="weight" type="hidden" id="weight-measure" value='' readonly="readonly" />
      </div>
    </div>
    <div class="bmi-height">
      <div class="form-horizontal">
        <label for="height">How tall are you?</label>
          <div class='input-group'>
              <input id="height-value-ft" class='control-group form-control' style="max-width: 50%;" type='text' name='height-name' placeholder='ft'/>
              <input id="height-value-in" class='control-group form-control' style="max-width: 50%;" type='text' name='height-name' placeholder='in'/>
              <span class='input-group-btn'>
                  <div class="btn-group">
                    <button type="button" class="btn bmi-btn  btn-block height active-height selected-height" id='ft-in'>ft-in</button>
                  </div>
              </span>
              <input id="height-value" class='control-group form-control ' type='text' name='height-name' placeholder='cm'/>
              <span class='input-group-btn '>
                  <div class="btn-group">
                    <button type="button" class="btn bmi-btn  btn-block height" id='cm'>cm</button>
                  </div>                        
              </span>
          </div>
        <input name="height" type="hidden" id="height-measure" value='' readonly="readonly" />
      </div>
    </div>
    <div class="bmi-result">
      <div class="form-horizontal">
      <label for="height">BMI Score</label>
        <div class='input-group'>
          <input id="bmi-result" class='form-control' type='text' name='result' value='' readonly="readonly" />
          <span class='input-group-btn'>
              <button id="cal-result" class='btn btn-default' type="button" >Health Status</button>
          </span>
        </div>
      </div>
    </div>
  </form>
</div> 

dietsource/templates/services/services_detail.html
{% extends 'layout/master.html' %}
{% load i18n static %}
    {% block extrastyle %}
    
   {% endblock %}
{% block content %}
<div class="container wrapper">
    <div class='col-md-8'>
        <article class="entry">
            <header class="entry-header">
                <h1 class="entry-title"> {{ service.title }}<small>{% if not service.publish_this_service %}<span style='color:red;'> *Draft*</span> {% endif %}</small></h1>
                <p class="entry-meta">
                <small>
                    <span class="entry-author">
                        By: {{ service.author.get_full_name }}
                    </span>
                    <span class="entry-category">
                        In: {{ service.all_categories }}
                    </span>
                    <span class="entry-service-date">
                        serviceed on: {{ service.published_on }}
                    </span>
                    <span class="entry-update-date">
                        Last updated: {{ service.last_updated|timesince }}
                    </span></small>
                </p>
            </header>
            <div class="entry-content">
                {% if service.featured_image %}
                    <img src="{{ service.featured_image.url }}" class="entry-featured-img img-responsive" alt="{{ service.title }}" >
                {% else %}
                <img src="/media/featured_service_images/default-featured-image.png" class="entry-featured-img img-responsive" alt="{{ service.title }}" >
                {% endif %}
                <hr>
                <div class="entry-content-service">
                    {{ service.content|safe}}
                </div>
                
            </div>
            <footer class="entry-footer">
                <div class="author-box">
                    
                </div>
            </footer>                
                
        </article>
</div>

</div>
{% endblock %}

dietsource/templates/services/services_list.html
{% extends 'layout/master.html' %}
{% load i18n static %}
    {% block extrastyle %}
    
   {% endblock %}
{% block content %}
<div class="container wrapper">
<div class="content">
	<div class="row">
		<div class="text-center ">
			<h2>Trending DietPlate Articles</h2>
		</div>
		{% for service in all_services %}
		<div class="card col-sm-4">
			<div class="card-thumb">
				{% if service.featured_image %}
                    <a href="{{ service.get_absolute_url }}" title="{{ service.name }}">
                        <img src="{{ service.featured_image.url }}" class="card-img img-responsive" alt="{{ service.name }}" >
                    </a>
                {% else %}
                    <a href="{{ service.get_absolute_url }}" title="{{ service.name }}">
                        <img src="/media/featured_post_images/default-featured-image.png" class="entry-featured-img img-responsive" alt="{{ service.name }}" >
                    </a>
                {% endif %}
			</div>

			<div class="card-meta">
				<h3 class="card-title">
					<a href="{{ service.get_absolute_url }}"> {{ service.name }}</a>
				</h3>
			</div>
			<div class=card-content>
              <p>{{ service.content|safe|striptags|truncatechars_html:200 }}</p>
            </div>
        <footer class="card-footer text-center">
            <p><a href="{{ service.get_absolute_url }}" class="btn btn-block btn-lg btn-warning count-read-button " role="button">Know More</a></p>
        </footer>  

		</div>
            {% endfor %}
	</div>
</div>

</div>
{% endblock %}