dietsource/blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	#home-page
    #url(r'^$', views.index , name="index" ),
    url(r'^blog/$', views.post_list , name="index" ),
    url(r'^faq/$', views.faq , name="faq" ),
    url(r'^category/(?P<cat_slug>[a-zA-Z0-9-]+)/$', views.category_list_view , name="category" ),
    url(r'^tag/(?P<tag_slug>[a-zA-Z0-9-]+)/$', views.tag_list_view , name="tag" ),
    url(r'^(?P<post_slug>[a-zA-Z0-9-]+)/$', views.post_detail , name="post" ),

]

dietsource/dietplate/urls.py
"""
Definition of urls for notesformca.
"""
from django.conf import settings
from django.conf.urls.static import static
from datetime import datetime
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
from . import views
admin.autodiscover()

urlpatterns = [
    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),


    # Uncomment the next line to enable the admin:

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^$', views.index , name="index" ),
    url(r'^about/$', views.about , name="about" ),
    url(r'^contact/$', views.contact , name="contact" ),
    url(r'^contact/success/$', views.contact_success , name="contact_success"),
    url(r'^book-appointment/$', views.book_appointment , name="book_appointment"),
    # url(r'^chaining/', include('smart_selects.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    #url(r'^service/', include("services.urls", namespace='service')),
    url(r'^', include('blog.urls', namespace = 'blog')),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

dietsource/templates/layout/about.html

  {% extends "layout/master.html" %}
    {% load i18n static %}

    {% block extrastyle %}
    <link href="{% static 'layout/css/dp-aboutus.css' %}" rel="stylesheet">
    {% endblock %}
    <!-- Intro Section -->
{% block content %} 
      <div class="wrapper">
      <div class="about-cover hidden-xs">
          <img class="img-responsive" style="width :100%;max-height: 350px;" src="{% static 'layout/img/dp-full.jpg' %}">
      </div>
      <div class="container aboutus bg">
           <div class="col-sm-5">
               <img class="img-responsive dikshadp" src="{% static 'layout/img/indoor_dp.jpg' %}">
           </div>
           <div class="col-sm-7">
            <div class="about-content">
                <p>In this hustle bustle of our super busy life, it has become even more difficult to take care of ourselves. Good health somehow gets pushed to the last in our priority list. At times it is that new body hugging dress that we bought that becomes an eye opener.</p><p>
Lost in this fast moving world, don't you think we have really taken our body for granted? What is it that we are not doing right? What is it that needs to fall in place? Diet. Obesity, PCOS, pregnancy, thyroid or whatever it is, your diet is your ultimate rescuer. The good news is the ideal diet for you is just one step away now. Meet Diksha Gulati and let her know you bodily concerns. She will take care of it all. Having worked with brands like Jeewan Mala Hospital and Fortis Hospital she is presently working with BLK hospital, Diksha has mastered the art of staying healthy or say keeping people healthy.</p>
<p>
Right food at right time is the key to ultra-right health.</p>
</div>
               
           </div>
      </div>

      </div>

{% endblock %}

{% block extrascript%}
{% endblock %}

dietsource/templates/layout/footer.html
{% load i18n static %}

<footer id="footer">
<div class="container" style="min-height: 50px;">
</div>

<section class="footer">
    <div class="container">
      <div class="row">
          <div class="col-lg-4  col-md-4 col-sm-4">
              <div class="footer_dv  wow slideInUp" data-wow-duration="300ms" data-wow-delay="100ms">
                  <h4>MENU</h4>
                  <ul>
               
                        <li><a href="{% url 'index' %}">HOME</a></li>
                        <li><a href="{% url 'about' %}">ABOUT US</a></li>
                        <li><a href="{% url 'blog:faq' %}">DIET FAQ</a></li>
                        <li><a href="{% url 'blog:index' %}">EXPLORE OUR BLOG</a></li>
                        <li><a href="{% url 'contact' %}">REACH TO US</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4  col-md-4 col-sm-4">

            </div>
            <div class="col-lg-4  col-md-4 col-sm-4 pull-right">
              <div class="footer_dv  wow fadeInUp" data-wow-duration="300ms" data-wow-delay="100ms">
                  <h4>Follow us :</h4>
                  <div class="contact-info">
                  <ul class="address">
                    <li><i class="fa fa-map-marker"></i> <span> Address:</span> BH-18 (East), Shalimar Bagh,New Delhi. </li>
                  <!--   <li><i class="fa fa-phone"></i> <span> Phone:</span> +928 336 2000  </li> -->
                    <li><i class="fa fa-envelope"></i> <span> Email:</span><a href="mailto:info@dikshagulatidietplate.com"> info@dikshagulatidietplate.com</a></li>
                  </ul>
                </div>  
                  <h4>Follow us :</h4>
                    <div class="social-icons">
                      <ul>
                        <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li> 
                        <li><a class="instagram" href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                      </ul>
                    </div>        
              </div>
            </div>
        </div>
    </div>
</section>
</footer>



dietsource/templates/layout/index.html

  {% extends "layout/master.html" %}
    {% load i18n static %}

    {% block extrastyle %}
    <link href="{% static 'layout/css/main_slider.css' %}" rel="stylesheet"> 
    {% endblock %}
    <!-- Intro Section -->
{% block content %} 
<div id="dietplate-slider" class="carousel bs-slider fade  control-round indicators-line text-center" data-ride="carousel" data-pause="hover" data-interval="5000" >

    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#dietplate-slider" data-slide-to="0" class="active"></li>
        <li data-target="#dietplate-slider" data-slide-to="1"></li>
        <li data-target="#dietplate-slider" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper For Slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <!-- Slide Background -->
            <img src="{% static 'layout/img/pic.jpg' %}" alt="Diksha Gulati - Quote"  class="slide-image"/>
            <div class="bs-slider-overlay"></div>
            <!-- Slide Text Layer -->
            <div class="slide-text slide_style_right">
                <h1 data-animation="animated zoomInLeft"><span>Dt. DIKSHA GULATI</span></h1>
                <p data-animation="animated fadeInRight">"To work smart and not hard on your body,<br>you need to <span>LIVE</span> right, <span>SLEEP</span> right, and <span>EAT</span> right"</p>
                <a href="{% url 'about' %}" class="btn btn-primary" data-animation="animated fadeInRight">Know More about us</a>
            </div>
        </div>
        <div class="item">
            <!-- Slide Background -->
            <img src="{% static 'layout/img/Fruits.jpg' %}" alt="Dietplate latest updates." class="slide-image"/>
            <div class="bs-slider-overlay"></div>
            <div class="container">
                <div class="row">
                    <!-- Slide Text Layer -->
                    <div class="slide-text slide_style_left">
                        <h1 data-animation="animated zoomInRight">EAT <span>HEALTHY</span><br>STAY <span>HEALTHY</span></h1>
                        <p data-animation="animated fadeInLeft">Read latest updates from our blog and know amazing <span>facts</span> or <span>tips</span> for a <span>healthy life</span>.</p>
                        <a href="{% url 'blog:index' %}"" class="btn btn-primary" data-animation="animated fadeInRight">Explore our Blog</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="item">
            <!-- Slide Background -->
            <img src="{% static 'layout/img/dp_door.jpg' %}" alt="Book an Appointment with Dietplate"  class="slide-image"/>
            <div class="bs-slider-overlay"></div>
            <!-- Slide Text Layer -->
            <div class="slide-text slide_style_center">
                <h1 data-animation="animated flipInX">BOOK AN <span>APPOINTMENT</span></h1>
                <p data-animation="animated lightSpeedIn">Give us a <span>visit at our Clinic</span></p>
                <a data-toggle="modal" data-target="#appoint" class="btn btn-primary" data-animation="animated fadeInUp">BOOK NOW</a>
            </div>
        </div>

    </div><!-- End of Wrapper For Slides -->

    <!-- Left Control -->
    <a class="left carousel-control" href="#dietplate-slider" role="button" data-slide="prev">
        <span class="fa fa-angle-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>

    <!-- Right Control -->
    <a class="right carousel-control" href="#dietplate-slider" role="button" data-slide="next">
        <span class="fa fa-angle-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>

</div> <!-- End  dietplate-slider Slider -->
    <section class=" parallax">
      <div class="container intro-section bg">
        <h1 align="center" class="about-info wow fadeInDown" data-wow-delay="300ms">KNOW YOUR BMI</h1>
          <div class="col-sm-7">
            <div class="about-info wow fadeInUp" data-wow-delay="300ms">
              <h3>Do you know?</h3>
              <p >Usually, BMI values of girls are slightly larger than boys (from age 7 to 16). As long as men and women are not overweight, BMI values of men are slightly larger than women ( after age 18).</p>
            </div>
          </div>
          <div class="col-sm-5">
          {% include 'services/bmiForm.html' %}

          </div>
      </div>
       
    </section>
{% endblock %}

{% block extrascript%}
    <script src="{% static 'layout/js/main_slider.js' %}"></script>
{% endblock %}

dietsource/templates/layout/master.html
{% load i18n static %}
{% load dp_form_tags %}
{% load dp_dropdown_menu %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <title>{% block head_title %}{% if title %}{{ title }} - {% endif%}DietPlate | Creating healthier lives{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'layout/img/dp-icon.png' %}"/>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="title" content="{{ title }}">
        <meta name="robots" content="noodp"/>

    {% block meta %}
        <meta name="description" content="{% block seodesc %}{% endblock %}">
        <meta name="author" content="{% block seoauth %}{% endblock %}">
    {% endblock meta %}


    {% block extrahead %}
    {% endblock %}

    <!-- Bootstrap Core CSS -->

    <link href="{% static 'layout/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" media="all">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" rel="stylesheet" media="all">

    <!-- Custom CSS -->
    <link href="{% static 'layout/css/scrolling-nav.css' %}" rel="stylesheet">
    <link href="{% static 'layout/css/dp-base.css' %}" rel="stylesheet">
    <link href="{% static 'layout/css/extra-tabs.css' %}" rel="stylesheet">
    <link href="{% static 'layout/css/bmiForm.css' %}" rel="stylesheet">
    
    <script src="{% static 'layout/js/jquery.js' %}"></script>
    {% block extrastyle %}
    
    
    {% endblock %}

<script type="text/javascript">

    $(window).load(function() {
        $("body").easeScroll();
        $(".loader").fadeOut("slow");
    })
    $(document).ready(function() {
        // get current URL path and assign 'active' class
        var pathname = window.location.pathname;
        $('.nav > li > a[href="'+pathname+'"]').addClass('active');
    })

</script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
{% load i18n %}


<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<div class="loader"></div> 
{% navigation %}
    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
    {% for message in messages %}
    <li>{{message}}</li>
    {% endfor %}
      </ul>
    </div>
    {% endif %}

<div class="appointment-form-tab">
<div class="panel panel-default" data-toggle="modal" data-target="#appoint">
    <div class="panel-leftheading">
        <h3 class="panel-lefttitle">Book an Appointment</h3>
    </div>
</div>
</div>

{% block content %}
{% endblock %}

{% appointment_form %}

{% include 'layout/footer.html' %}

    <!-- jQuery -->
      <a class="page-scroll scrollToTop" href="#page-top" ><span class="glyphicon glyphicon-upload" aria-hidden="true"></span></a>  

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'layout/js/bootstrap.min.js' %}"></script>

    <!-- Scrolling Nav JavaScript -->
    <script src="{% static 'layout/js/bmiForm.js' %}"></script>
    <script src="{% static 'layout/js/wow.min.js' %}"></script>
    <script src="{% static 'layout/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'layout/js/scrolling-nav.js' %}"></script>
    <script src="{% static 'layout/js/mousescroll.js' %}"></script>
    <script src="{% static 'layout/js/ajax_form.js' %}"></script>
    <script type="text/javascript">
        new WOW().init();
    </script>


{% block extrascript%}
{% endblock %}

</body>

</html>

dietsource/templates/layout/navbar.html
   {% load i18n static %}
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                
                    <i class="navbar-toggle-caret fa fa-caret-square-o-down fa-2x pull-right" aria-hidden="true" data-toggle="collapse" data-target=".navbar-ex1-collapse"></i>
               
                <a class="navbar-brand" href="{% url 'index' %}"> <img class="logo-img img-responsive" src="{% static 'layout/img/logo.png' %}"></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav text-center">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                   <!--  <li class="hidden">
                        <a class="page-scroll" href="#page-top"></a>
                    </li> -->
                    <li>
                        <a class="" href="{% url 'about' %}">ABOUT US</a>
                    </li>
                    <li>
                        <a class="" href="{% url 'blog:faq' %}">DIET FAQ</a>
                    </li>
                     <li>
                        <a class="" href="{% url 'blog:index' %}">BLOG</a>
                    </li>
                    <li>
                        <a class="" href="{% url 'contact' %}">REACH TO US</a>
                    </li>                    
                        
                </ul>
                <span class="pull-right call-action hidden-xs" data-toggle="modal" data-target="#appoint">
                    <a href="#" class="button"></i>REQUEST A CALL</a>
                </span>
                
            <!-- /.navbar-collapse -->
        </div>
        
        <!-- /.container -->
        </div>
    </nav>